/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: MOJackal (https://sketchfab.com/MOJackal)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/satellite-51b687b2effb4bd9a1176a8d45b7157d
title: Satellite
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Satellite(props) {
  const { nodes, materials } = useGLTF("/satellite.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale = {1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.d_gray}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.l_gray}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.solar_panels}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.white}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.plate}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/satellite.glb");
